server:
  port: 9081
#  ssl:
#    key-store: 'classpath:residentid.p12'
#    key-store-password: Anid_2022
#    key-store-type: pkcs12
#    key-alias: residentid.anid.tg (acme client)
#    key-password: Anid_2022
  tomcat:
    basedir: ${spring.application.basedir}/tomcat
    accesslog:
      enabled: true
      directory: "logs"
      buffered: false
      suffix: .json
      rotate: true
      max-days: 3
      rename-on-rotate: true
      pattern: '{"clientIp":"%h","user":"%l","username":"%u","time":"%{yyyy-MM-dd''T''HH:mm:ss.SSS''Z''}t","urlPath":"%U","duration":"%D","method":"%m","request":"%r","status":"%s","responseSize":"%b","trace":"%{X-B3-TraceId}i","span":"%{X-B3-SpanId}i"}'

activemq:
  broker:
    url: "tcp://localhost:61616"
spring:
  application:
    name: residentid-deduplication-service
    description: Gestion de la deduplication des biométries de
    basedir: ${user.home}/.${spring.application.name}
  datasource:
    database: residentid_prod_db_v10 #bd_3 #residentid_preprod_db_v4
    hostname: 10.40.40.19 #localhost #10.40.40.19
    port: 5432
    username: postgres #francis postgres
    password: postg_anid #Anid2022 postg_anid
    url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database}?useSSL=false&serverTimezone=UTC&useLegacyDatetime=false
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: "SELECT 1"
      max-lifetime: 1800000
      idle-timeout: 600000
      leak-detection-threshold: 60000
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none

app:
  deduplication:
    treshold: 25

logging:
  config: 'classpath:logback-spring.xml'
  file:
    path: ${spring.application.basedir}/lts/logs
